
version: '3.2'
services:
    app:
        build:
            context: .
            dockerfile: docker/app.dockerfile
        volumes:
            - .:/app

    php:
        build:
            context: .
            dockerfile: docker/php.dockerfile
        volumes:
            - .:/app
        ports:
            - 9000:9000

    nginx:
        image: nginx:latest
        volumes:
            - .:/app
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 8080:80


