version: 3
services:
    app:
        build: .
    nginx:
        image: nginx
        volumes:
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 80:80
    php: