
version: '2'
services:

    app:
        build:
            context: ./
            dockerfile: docker/app.dockerfile
        working_dir: /var/www
        volumes:
            - .:/var/www
        ports:
            - 8000:8000
        environment:
            - "DB_PORT=3306"
            # - "DB_HOST=mysql"

    nginx:
        # build:
        #     context: ./
        #     dockerfile: docker/web.dockerfile
        image: nginx:1.10
        working_dir: /var/www
        volumes_from:
            - app
        volumes:
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 8080:80
    # mysql:
    #     image: mysql:5.7
    #     volumes:
    #         - dbdata:/var/lib/mysql
    #     environment:
    #         - "MYSQL_DATABASE=homestead"
    #         - "MYSQL_USER=homestead"
    #         - "MYSQL_PASSWORD=secret"
    #         - "MYSQL_ROOT_PASSWORD=secret"
    #     ports:
    #         - "33061:3306"

volumes:
    dbdata: