
version: '3.2'
services:
    app:
        build:
            context: .
            dockerfile: docker/app.dockerfile
        volumes:
            - .:/app

    php:
        build:
            context: ./docker
            dockerfile: php.dockerfile
        volumes:
            - .:/app
        ports:
            - 9000:9000
        networks:
            - backend
        links:
            - app

    nginx:
        build:
            context: ./docker/nginx
        volumes:
            - .:/app
        ports:
            - 8080:80
        links:
            - php
        networks:
            - frontend
            - backend


networks:
    frontend:
        driver: "bridge"
    backend:
        driver: "bridge"
